### PR TITLE
Api base.

### PR DESCRIPTION
**Pull request by LunatickDuck**
After reading #104 I was seduced by the idea.

I'm not a js guru and this code have to be improved a lot (new preset, some easy-to-uses functions...) but I create this PR before continues in order to know if this little base is good or if I should change it.

### CODE REVIEW

**Comment by jettero** [comment]
heh, am I reading this wrong; or has this PR been open since 2014?

**Comment by lgarron** [comment]
> heh, am I reading this wrong; or has this PR been open since 2014?

It has been open!

alg.cubing.net v2 is still far from ready, although I'm working on it on-off.

**Comment by jettero** [comment]
It looks like this project had a lot of initial momentum, then life happened. I've got a bunch of projects like that in my github.

Is there any way to resurrect time/impetus/interest to get a v2 out there? Maybe I'm misreading. I'll go look at the v2 branch(es).

**Comment by lgarron** [comment]
> Is there any way to resurrect time/impetus/interest to get a v2 out there? Maybe I'm misreading. I'll go look at the v2 branch(es).

Sorry, I can't promise anything. I have time to work on it every few months, but at the moment I'm focusing on getting things right rather than finishing sooner.

**Comment by lgarron** [comment]
`cubing.js` now has this functionality, particularly for Twizzle.

**Pull request closed without merging**
