### PR TITLE
Update WR solve

### PR DESCRIPTION
**Pull request by supersammy7000**

### CODE REVIEW

**Comment by lgarron** [comment]
Could you let me know where you got this from?

It doesn't seem to match the reconstructions at https://www.speedsolving.com/forum/threads/feliks-zemdegs-4-73-3x3-single.63195/page-2

**Comment by supersammy7000** [comment]
I got the reconstruction from https://www.youtube.com/watch?v=t_1EncFk34g Sorry I didn't check other sources.

**Comment by supersammy7000** [comment]
I fixed the reconstruction and I updated the readme with the new WR.

**Comment by lgarron** [comment]
This is out of date by now.

**Pull request closed without merging**
